--creacion de la tabla
CREATE TABLE IF NOT EXISTS gente(
    idpersona INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombrepersona varchar(255) NOT NULL,
    idprogenitor INTEGER REFERENCES gente(idpersona)
)


--creacion de los usuarios
insert into gente(nombrepersona,idprogenitor) values('mariana',null);
insert into gente(nombrepersona,idprogenitor) values('paula',1);
insert into gente(nombrepersona,idprogenitor) values('fernanda',1);
insert into gente(nombrepersona,idprogenitor) values('bryan',2);
insert into gente(nombrepersona,idprogenitor) values('paul',2);
insert into gente(nombrepersona,idprogenitor) values('christhen',3);


--consulta para generaciones de un arbol 
;WITH RECURSIVE rec AS (
        SELECT idpersona, nombrepersona,idprogenitor, 0 AS contador
        FROM gente
        WHERE idpersona = 1     
		UNION ALL
        SELECT e.idpersona, e.nombrepersona, e.idprogenitor ,rec.contador + 1 AS contador
        FROM gente e
        JOIN rec ON e.idprogenitor = rec.idpersona
)
select * from rec where contador = 0



